### ISSUE TITLE
Witchery (just a comment)

### ISSUE THREAD

**Issue by jlblancoc** [facontidavide/mcap_editor#3]
Wow, great app, Davide! :-) 

I'm just curious about the link between this repo and netlify. I have manually deployed emscripten apps in the past, but it was a pain, even without Qt, so I wonder if there is any way to make this kind of apps easier. 

Thanks!

**Comment by facontidavide** [comment]
This is qt wasm

**Comment by jlblancoc** [comment]
Thanks for the pointers! :muscle:
